Docker 4
Otus-DevOps-2021-11/SedovSG_microservices pull request #4
Opened 2022-02-13 20:17 UTC by SedovSG

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Использование переменных окружения в Docker Compose
 - Применение `docker-compose.override` для сборки проекта в `dev` режиме

## Как запустить проект:
 - docker-compose up --build -d

2022-02-13 20:28 UTC, SedovSG commented
Не правильное поведение тестов. Команда `cat -e src/docker-compose.yml` возвращает $, что говорит о новой строке, но тест проваливается. Более того тест не может обнаружить файл `src/.env.examle`, который явно лежит в репозитории.

2022-02-14 08:36 UTC, mrgreyves requested changes
Здравствуйте!)
А вот тут вам не хватает файлика
На исправление думаю не уйдет много времени =)

2022-02-15 05:38 UTC, SedovSG commented
Как писал уже выше, файлик в репозитории - src/.env.example

2022-02-15 10:12 UTC, mrgreyves requested changes
Здравствуйте!)
У вас не хватает  +.IOError: [Errno 2] No such file or directory: './docker-compose.yml'
С env там все впорядке =)

2022-02-15 13:21 UTC, SedovSG commented
Здравствуйте. Действительно, почему-то docker-compose.yml оказался в .gitignore
Но всё та же ошибка теста, с проверкой 5000 порта (

2022-02-15 20:14 UTC, mrgreyves approved these changes
Здравствуйте!)
Даааа, в последнее время достаточно приключений с днсом и тестами =)

2022-02-16 04:44 UTC, merged